#!/usr/bin/env bash

GTK_THEME_NAME="FlatColor"
# Icon theme color modified variant
GTK_ICON_THEME_NAME="Tela-${COLOR[cursor]:-default}${BRIGHT_VARIANT}"
GTK_FONT_NAME="Noto Sans 11"

GTK_TOOLBAR_STYLE="GTK_TOOLBAR_ICONS"
GTK_TOOLBAR_ICON_SIZE="GTK_ICON_SIZE_SMALL_TOOLBAR"
GTK_BUTTON_IMAGES=0
GTK_MENU_IMAGES=0
GTK_DECORATION_LAYOUT="menu:"

COLOR[selection_foreground]=#000000
COLOR[selection_background]=#FFFACD

COLOR[url_color]=#93B9D9
COLOR[highlight]=#E45959

COLOR[cursor]=${COLOR[10]}
