#!/bin/bash

declare -A COLOR

# -----------------------------------------------------------------------------
# https://www.reddit.com/r/unixporn/comments/nbxxgk/bspwm_polybar_just_presenting_my_desktop_after_a/
# -----------------------------------------------------------------------------

export COLOR=(
    # terminal colors+
    # black
    [0]=#2F2E2C
    [8]=#494844

    # red
    [1]=#A26666
    [9]=#D78788

    # green
    [2]=#90A57E
    [10]=#AFBDA3

    # yellow
    [3]=#D6AF86
    [11]=#E4C9AE

    # blue
    [4]=#7FA5BC
    [12]=#A2BDCE

    # magenta
    [5]=#C79FC4
    [13]=#D7BEDB

    # cyan
    [6]=#8ADAB3
    [14]=#B2E7DD

    # white
    [7]=#D0D0D0
    [15]=#EFEFEF
)
