#!/bin/bash

declare -A COLOR

# -----------------------------------------------------------------------------
# https://www.reddit.com/r/unixporn/comments/nbxxgk/bspwm_polybar_just_presenting_my_desktop_after_a/
# -----------------------------------------------------------------------------

export COLOR=(
    # black
    [0]=#2F2E2C
    # red
    [1]=#A26666
    # green
    [2]=#90A57E
    # yellow
    [3]=#D6AF86
    # blue
    [4]=#7FA5BC
    # magenta
    [5]=#C79FC4
    # cyan
    [6]=#8ADAB3
    # white
    [7]=#D0D0D0
)
