#!/bin/bash

declare -A COLOR

# -----------------------------------------------------------------------------
# Tango color cheme
# -----------------------------------------------------------------------------

export COLOR=(
    [name]="Tango"
    [description]=""

    # terminal colors+
    # black
    [0]=#282a2e
    [8]=#373b41

    # red
    [1]=#a54242
    [9]=#cc6666

    # green
    [2]=#8c9440
    [10]=#b5bd68

    # yellow
    [3]=#de935f
    [11]=#f0c674

    # blue
    [4]=#5f819d
    [12]=#81a2be

    # magenta
    [5]=#85678f
    [13]=#b294bb

    # cyan
    [6]=#5e8d87
    [14]=#8abeb7

    # white
    [7]=#707880
    [15]=#c5c8c6
)
