#!/bin/bash

declare -A COLOR

# -----------------------------------------------------------------------------
# Mars color cheme
# -----------------------------------------------------------------------------

export COLOR=(
    [name]="Mars"
    [description]=""

    ## terminal colors+
    # black
    [0]=#343945
    [8]=#4F4F5F

    # red
    [1]=#713F3F
    [9]=#8A4D4D

    # green
    [2]=#6D4C4C
    [10]=#875E5E

    # yellow
    [3]=#8D4F5A
    [11]=#A65D6A

    # blue
    [4]=#515D73
    [12]=#5C6473

    # magenta
    [5]=#774B5F
    [13]=#8D5871

    # cyan
    [6]=#A4A2AA
    [14]=#BBB7BF

    # white
    [7]=#E5E9F0
    [15]=#ECEFF4
)
